### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [conchoecia/pauvre#1]
Hi There,
running it without specific output format as follows: pauvre marginplot --fastq my.fastq
gave me the following error 
Traceback (most recent call last):
  File "/Users/ben/anaconda3/bin/pauvre", line 11, in <module>
    sys.exit(main())
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/pauvre/pauvre_main.py", line 146, in main
    args.func(parser, args)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/pauvre/pauvre_main.py", line 47, in run_subtool
    submodule.run(parser, args)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/pauvre/marginplot.py", line 276, in run
    marginplot(args)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/pauvre/marginplot.py", line 273, in marginplot
    plt.savefig(outname, transparent=args.transparent)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 696, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py", line 1563, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2139, in print_figure
    canvas = self._get_output_canvas(format)
  File "/Users/ben/anaconda3/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2079, in _get_output_canvas
    '%s.' % (format, ', '.join(formats)))
ValueError: Format "p" is not supported.
Supported formats: bmp, eps, gif, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff.

**Comment by BenjaminSchwessinger** [comment]
I would also suggest to remove any use of latex in marginplot as this won't be installed by all users.   Set
  'text.usetex'         : False     ,
'text.latex.unicode' : False })

**Comment by conchoecia** [comment]
Congrats on opening issue #1! Thanks for the suggestions. I had to fix an error with the default value for the type argument.
