### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable

### ISSUE THREAD

**Issue by conchoecia** [conchoecia/pauvre#2]
```
Namespace(command='marginplot', dpi=600, fastq='1D_raw_1.0.3_bcd.fastq', fileform=['pdf', 'png'], func=<function run_subtool at 0x7f3bd8040f28>, lengthbin=None, maxlen=None, maxqual=None, qualbin=None, quiet=False, title='Read length vs mean quality.', transparent=True)
Traceback (most recent call last):
  File "/home/dschultz/python/anaconda3/bin/pauvre", line 11, in <module>
    sys.exit(main())
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/pauvre/pauvre_main.py", line 144, in main
    args.func(parser, args)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/pauvre/pauvre_main.py", line 47, in run_subtool
    submodule.run(parser, args)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/pauvre/marginplot.py", line 294, in run
    marginplot(args)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/pauvre/marginplot.py", line 134, in marginplot
    fig = plt.figure(figsize=(figWidth,figHeight))
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/dschultz/python/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
```

was running this on a server and encountered this error. produced neither pdf nor png.

**Comment by conchoecia** [comment]
trying https://github.com/matplotlib/matplotlib/issues/3466/#issuecomment-195899517

**Comment by smpcolston** [comment]
I'm not sure if this is related to this but I'm not getting a PNG or PDF, although I'm also not getting any errors after executing. I'm running this on a Mac. Thanks!
