### ISSUE TITLE
missing 1 required positional argument: 'histogram'

### ISSUE THREAD

**Issue by scogi** [conchoecia/pauvre#22]
Hi conchoecia

I just updated pauvre to the most recenet version 0.1.7 and run it, but it required scipy to be installed. After installing scipy, (sudo pip3 install scipy), I now get the following error:

`$ pauvre marginplot -f barcode07.fastq
Traceback (most recent call last):
  File "/usr/local/bin/pauvre", line 9, in <module>
    load_entry_point('pauvre==0.1.7', 'console_scripts', 'pauvre')()
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 302, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 57, in run_subtool
    submodule.run(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 370, in run
    margin_plot(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 185, in margin_plot
    stats(args.fastq, read_lengths, read_mean_quals)
TypeError: stats() missing 1 required positional argument: 'histogram'`

Python version is Python 3.6.1 (miniconda version)
How can I fix this? Thank you! 

best regards
sc

Best

**Comment by conchoecia** [comment]
Hi @scoa-git, looks like I forgot one little bit of code. I just updated the git repo and the package on `pip`. I recommend updating with `pip3` like in the README, then try again!

**Comment by scogi** [comment]
hi
works like a charm. thanks.
