### ISSUE TITLE
Argument error after clean installation

### ISSUE THREAD

**Issue by GeoMicroSoares** [conchoecia/pauvre#25]
Hey there,

Am getting the following after a clean installation of pauvre:
```
$ pauvre --version
Traceback (most recent call last):
  File "/usr/local/bin/pauvre", line 9, in <module>
    load_entry_point('pauvre==0.1.84', 'console_scripts', 'pauvre')()
  File "/usr/local/lib/python3.5/dist-packages/pauvre/pauvre_main.py", line 155, in main
    information to stdout.""")
  File "/usr/lib/python3.5/argparse.py", line 1353, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1716, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1557, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1367, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.5/argparse.py", line 1506, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.5/argparse.py", line 1515, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -q/--quiet: conflicting option strings: -q, --quiet
```

**Comment by wdecoster** [comment]
Looks like this is because the --quiet argument was defined twice. Once in the class ArgumentParserWithDefaults and once in the main() function. Could quite easily be fixed (e.g. removing the one in the main() function, but I'm a bit reluctant to touch it because I don't know why it was implemented as such.

I can fix this in a few hours tonight - going home now.

**Comment by conchoecia** [comment]
Whoops! Looks like I didn't catch that `--quiet` had already been implemented. Don't code while jetlagged, folks. It should work now, @GeoMicroSoares.
