### ISSUE TITLE
TypeError: print_images() got an unexpected keyword argument 'base_output_name'

### ISSUE THREAD

**Issue by jpummil** [conchoecia/pauvre#37]
Installed using conda...no errors during install. BUT...while pauvre generates and outputs text stats to terminal, it gives an error when trying to generate/display the marginplot graphic image:

TypeError: print_images() got an unexpected keyword argument 'base_output_name'

Command line issued: pauvre marginplot --fastq ecoli_p4_filtered.fastq

This happens both on a Mac as well as a Linux system...

**Comment by jpummil** [comment]
Full error below:

/Users/jpummil/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "/Users/jpummil/anaconda3/bin/pauvre", line 10, in <module>
    sys.exit(main())
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/pauvre_main.py", line 405, in main
    args.func(parser, args)
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/pauvre_main.py", line 65, in run_subtool
    submodule.run(args)
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 383, in run
    margin_plot(df=df.dropna(), **vars(args))
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 340, in margin_plot
    y_label='Read Length', bottom_spine=length_bottom_spine)
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 117, in generate_histogram
    bins = np.arange(0, max_plot_length, bin_interval)
ZeroDivisionError: division by zero

**Comment by jpummil** [comment]
Full error below:

/Users/jpummil/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "/Users/jpummil/anaconda3/bin/pauvre", line 10, in <module>
    sys.exit(main())
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/pauvre_main.py", line 405, in main
    args.func(parser, args)
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/pauvre_main.py", line 65, in run_subtool
    submodule.run(args)
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 383, in run
    margin_plot(df=df.dropna(), **vars(args))
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 340, in margin_plot
    y_label='Read Length', bottom_spine=length_bottom_spine)
  File "/Users/jpummil/anaconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 117, in generate_histogram
    bins = np.arange(0, max_plot_length, bin_interval)
ZeroDivisionError: division by zero

**Comment by the-tech-mode** [comment]
Hello 
I got something very similar 
Has anyone figured out how to solve this issue?

TypeError: print_images() got an unexpected keyword argument 'base_output_name'

full error below 
----

Traceback (most recent call last):
  File "/home/luna2/pauvre/pauvre/pauvre_main.py", line 640, in <module>
    main()
  File "/home/luna2/pauvre/pauvre/pauvre_main.py", line 634, in main
    args.func(parser, args)
  File "/home/luna2/pauvre/pauvre/pauvre_main.py", line 64, in run_subtool
    submodule.run(args)
  File "/home/luna2/.local/lib/python3.6/site-packages/pauvre/marginplot.py", line 408, in run
    margin_plot(df=df.dropna(), **vars(args))
  File "/home/luna2/.local/lib/python3.6/site-packages/pauvre/marginplot.py", line 397, in margin_plot
    transparent=kwargs["TRANSPARENT"])
TypeError: print_images() got an unexpected keyword argument 'base_output_name'



------

thank you 

Hector

**Comment by Koen-vdl** [comment]
Hi, 
I encountered the same issue while running pauvre. I tried a pip3 install. I also tried a conda install on a different system. Same issue. 

>pauvre marginplot --fastq 2016-11058_Filtered.fastq.gz
Stats get correctly displayed but then the following is printed to the screen:

Traceback (most recent call last):
  File "/home/kvandelannoo/miniconda3/bin/pauvre", line 10, in <module>
    sys.exit(main())
  File "/home/kvandelannoo/miniconda3/lib/python3.7/site-packages/pauvre/pauvre_main.py", line 634, in main
    args.func(parser, args)
  File "/home/kvandelannoo/miniconda3/lib/python3.7/site-packages/pauvre/pauvre_main.py", line 64, in run_subtool
    submodule.run(args)
  File "/home/kvandelannoo/miniconda3/lib/python3.7/site-packages/pauvre/marginplot.py", line 408, in run
    margin_plot(df=df.dropna(), **vars(args))
  File "/home/kvandelannoo/miniconda3/lib/python3.7/site-packages/pauvre/marginplot.py", line 397, in margin_plot
    transparent=kwargs["TRANSPARENT"])
TypeError: print_images() got an unexpected keyword argument 'base_output_name'

**Comment by conchoecia** [comment]
This appears to be working in the current version. Closing for now. Please reopen if there is a problem.
