### ISSUE TITLE
test failure with biopython 1.80

### ISSUE THREAD

**Issue by emollier** [conchoecia/pauvre#45]
Hi,

While introducing biopython 1.80 in Debian experimental, I noticed in [Debian Bug#1024835] that pauvre fails when trying to run test suites with:
```
$ python3 -m unittest discover -v
```

The error log shows:
```
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pauvre/build/pauvre/pauvre_main.py", line 636, in <module>
    main()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pauvre/build/pauvre/pauvre_main.py", line 630, in main
    args.func(parser, args)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pauvre/build/pauvre/pauvre_main.py", line 62, in run_subtool
    import pauvre.synplot as submodule
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pauvre/build/pauvre/synplot.py", line 46, in <module>
    import Bio.SubsMat.MatrixInfo as MI
ModuleNotFoundError: No module named 'Bio.SubsMat'
```

This seems to be related to the module Bio.SubsMat being unmaintained in biopython since 1.75; it is quite possible it has been removed in version 1.80.  Their [NEWS.rst] states regarding version 1.75:

> A new module substitution_matrices was added to Bio.Align, which includes an Array class that can be used as a substitution matrix. As the Array class is a subclass of a numpy array, mathematical operations can be applied to it directly, and C code that makes use of substitution matrices can directly access the numerical values stored in the substitution matrices. This module is intended as a replacement of Bio.SubsMat, which is currently unmaintained.

In hope this helps,
Étienne.

[Debian Bug#1024835]: https://bugs.debian.org/1024835
[NEWS.rst]: https://github.com/biopython/biopython/blob/master/NEWS.rst

**Comment by emollier** [comment]
Thanks for merging the patch.  I guess the issue can be closed now.

Have a nice day,  :)
Étienne.
