### ISSUE TITLE
Error using marginplot

### ISSUE THREAD

**Issue by desmodus1984** [conchoecia/pauvre#48]
Hi,

I am interested in plotting the quality-score vs sequence-length, and I tried marginplot after installing the software in conda, and it produced me an error.
I followed the code, mine was:
`pauvre marginplot --fastq Ju760.Lig.P-1.fastq 
`

I got the stats back but then I got the error:
Traceback (most recent call last):
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/matplotlib/__init__.py", line 732, in __setitem__
    cval = self.validate[key](val)
KeyError: 'text.latex.unicode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/juaguila/miniconda3/envs/NGS-manip/bin/pauvre", line 10, in <module>
    sys.exit(main())
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/pauvre/pauvre_main.py", line 630, in main
    args.func(parser, args)
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/pauvre/pauvre_main.py", line 64, in run_subtool
    submodule.run(args)
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/pauvre/marginplot.py", line 403, in run
    margin_plot(df=df.dropna(), **vars(args))
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/pauvre/marginplot.py", line 197, in margin_plot
    rc.update_rcParams()
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/pauvre/rcparams.py", line 7, in update_rcParams
    rcParams.update({
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/_collections_abc.py", line 999, in update
    self[key] = other[key]
  File "/home/juaguila/miniconda3/envs/NGS-manip/lib/python3.10/site-packages/matplotlib/__init__.py", line 737, in __setitem__
    raise KeyError(
KeyError: 'text.latex.unicode is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

I check the environment, and I have all the required apps in the conda environment.

Could you tell what happened or caused it?
The file I wanted to check is basically a fastq file with about 2.3 GB of data, average length of 5.1 kb and max 240kb.

Thanks;

Juan Pablo

**Comment by hempelc** [comment]
I have the same issue!

**Comment by safrye** [comment]
For the time being I just commented out the line with the parameter in rcparams.py like this:
<pre>
        'text.usetex'         : False     ,
#        'text.latex.unicode'  : False
 })
</pre>

After that I got the error:
<pre>
  File "/home/sfrye/miniforge3/lib/python3.12/site-packages/pauvre/marginplot.py", line 381, in margin_plot
    if kwargs["BASENAME"] is None and not kwargs["path"] is None:
                                          ~~~~~~^^^^^^^^
</pre>
when generating a marginplot. By adding the option -o to the command line I got rid of that error too.
<pre>
-o BASENAME, --output_base_name BASENAME
                        Specify a base name for the output file(s). The input file base name is the default
</pre>

Cheers.
